lines = { ...
'', ...
'obj Guild {',...
'intermediate A 1+5*3/(3+5);',...
'intermediate B 5+5-3/(3*(2/3)+(2)+5);',...
'};', ...
'', ...
'obj Guild2 { ', ...
'', ...
'};',...
' '};
buffer = sprintf('%s\n', lines{:});
Parser(buffer).parse();

% obj Guild { dynamic B; }
% obj Fish(Guild) { B=10; }
% obj[i=1..10] Fishes(Guild) { B=[10,20,20]; }