classdef WEBProgram

    properties
    end
    methods
        function this = WEBProgram()
            disp('Creating model');
            %this.model = ATNModel('Model','Add description...');
            %producers = ATNProducerGroup('Producers','');
            %this.model.add(producers);
            %producers.add(ATNProducer('Alg1','Desc',1,1));
            %producers.add(ATNProducer('Alg2','Desc',1,1));
            %producers.add(ATNProducer('Alg3','Desc',1,1));
            %this.model = migration('1_LakeConstance.mat');
        end
        
        function html = event(this, data)
            if strcmp(data.event,'addproducer')
                this.model.get_default_producer_group().add(ATNProducer([],'Add description...',1,1,0.2));
                html=this.model.get_trophic_view_html();
            else
                html=sprintf("Unknown event");
            end
        end
        
        function html = get_run_view_html(this)
             runner = ATNRunner(this.model);
             results = runner.run(4);
             html = results.get_html();
             html
        end

        function html = get_analyze_view_html(this)
            html=sprintf('%s\n',...
                '<div id="runresults">No results. Run the simulation first.</div>');
        end

        function html = get_trophic_view_html(this, data)
            html='';
                %html = this.model.get_trophic_view_html();
        end

        function html = get_build_view_html(this, data)
            html='';
                %html = this.model.get_build_view_html();
        end

        function json = get_treeview_json(this)
           json = jsonencode(this.model.treeview());
        end
        
        function html = get_html(this)
            html = sprintf('%s\n',...
'<!DOCTYPE html>',...
'<html lang="en">',...
'<head>',...
'<title>Allometric Trophic Network Dynamics</title>',...
'<meta charset="utf-8">',...
'<meta name="viewport" content="width=device-width, initial-scale=1">',...
'<link rel="stylesheet" href="themes/default/style.css" />',...
 '<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>',...
'<style>',...
'* {',...
'  box-sizing: border-box;',...
'}',...
'',...
'html {min-height: 100% !important; height: 100%;} body {',...
'  margin: 0;',...
'}',...
'',... %'h1 { margin-block-start: 0.23em; margin-block-end: 0.23em; }',... %'h2 { margin-block-start: 0.11em; margin-block-end: 0.11em; }',...
'.header {',...
'  background-color: #ffeed9;',...
'  padding: 5px; margin:0;',...
'  text-align: center;',...
'}',...
'',...
'.topnav {',...
'  overflow: hidden;',...
'  background-color: #fff;',...
'}',...
'.producertext { padding:8px 0px }',...
'.detritustext { padding:8px 0px }',...
'.consumertext { padding:8px 0px }',...
'.fishtext { padding:8px 0px }',...
'.topnav a {',...
'  float: left;',...
'  display: block;',...
'  color: #000000;',...
'  text-align: center;',...
'  padding: 14px 16px;',...
'  text-decoration: none;',...
'}',...
'',...
'.topnav a:hover {',...
'  background-color: #eee;',...
'  color: black;',...
'}',...
'',...
'.menucolumn {',...
'  float: left;',...
'  width: 5%;',...
'  text-align: center;',...
'  padding: 4px;',...
'}',...
'.producergroup {',... %'  border-style:dotted;',...'  display: inline-block;',...
'  float: left;',...%'  width:150px; height:400px;',...%' overflow: hidden;',...
' position: absolute;',...
'}',...
'.consumergroup {',... %'  border-style:dotted;',...'  display: inline-block;',...
'  float: left;',...%'  width:150px; height:400px;',... %' overflow: hidden;',...
' position: absolute;',...
'}',...
'.fishgroup {',... %'  border-style:dotted;',...'  display: inline-block;',...
'  float: left;',...%'  width:150px; height:400px;',... %' overflow: hidden;',...
' position: absolute;',...
'}',...
'.detritusgroup {',... %'  border-style:dotted;',...'  display: inline-block;',...
'  float: left;',...%'  width:150px; height:400px;',... %' overflow: hidden;',...
' position: absolute;',...
'}',...
'.propertycolumn {',...
'  float: left;',...
'  width: 25%;',...
'  padding: 4px;',...
'}',...
'.maincolumn {',...
'  float: left;',...
'  position: relative;',... 
' overflow:hidden;',...
'  width: 70%; min-height:600px;',...
'  padding: 4px;',...
'}',...
'',...
'.row:after {',...
'  content: "";',...
'  display: table;',...
' position: absolute; height:100%;',...
'  clear: both;',...
'}',...
'.on { background-color:#ffeed9; }',...
'.button {',...
'  background-color: #E07055;',...
'  border: none;',...
'  color: white; width: 100%;',...
'  padding: 1px;',...
'  text-align: center;',...
'  text-decoration: none;',...
'  font-size: 16px;',...
'  margin: 1px 1px;',...
'  border-radius: 12px;',...
'  border-width: 1px;',...
'  border-color: #704033; border-style:solid;',...
'  cursor: pointer;',...
'}',...
'.moveable { position: absolute; cursor: all-scroll; }',...
'.producerguild {',...
'  background-color: #2de0a5;',...
'  color: black; width: 60px;',...
'  padding: 0px 4px;',...
'  text-align: center;',...
'  text-decoration: none;',...
'  font-size: 10px;',...
'  margin: 1px 1px;',...
'  border-radius: 3px;',...
'  border-width: 1px;',...
'  border-color: #704033; border-style:solid;',...
'  cursor: unset;',...
'}',...
'.consumerguild {',...
'  background-color: #c9c06f;',...
'  color: black; width: 50px;',...
'  padding: 0px 2px;',...
'  text-align: center;',...
'  text-decoration: none;',...
'  font-size: 10px;',...
'  margin: 1px 1px;',...
'  border-radius: 50%;',...
'  border-width: 1px;',...
'  border-color: #704033; border-style:solid;',...
'  cursor: unset;',...
'}',...
'.detritusguild {',...
'  background-color: #75432a;',...
'  color: black; width: 50px;',...
'  padding: 0px 2px;',...
'  text-align: center;',...
'  text-decoration: none;',...
'  font-size: 10px;',...
'  margin: 1px 1px;',...
'  border-radius: 50%;',...
'  border-width: 1px;',...
'  border-color: #704033; border-style:solid;',...
'  cursor: unset;',...
'}',...
'.fishguild {',...
'  background-color: #FA8072;',...
'  color: black; width: 100px;',...
'  padding: 0px 2px;',...
'  text-align: center;',...
'  text-decoration: none;',...
'  font-size: 10px;',...
'  margin: 1px 1px;',...
'  border-radius: 50%;',...
'  border-width: 1px;',...
'  border-color: #704033; border-style:solid;',...
'  cursor: unset;',...
'}',...
'.demotree { overflow:auto; border:1px solid silver; min-height:600px; }',...
'@media screen and (max-width:600px) {',...
'  .column {',...
'    width: 100%;',...
'  }',...
'}',...
'ul, #myUL { list-style-type: none;}',...
'#myUL { margin: 0; padding: 0; }',...
'.caret { cursor: pointer;',...
'  -webkit-user-select: none; /* Safari 3.1+ */',...
'  -moz-user-select: none; /* Firefox 2+ */',...
'  -ms-user-select: none; /* IE 10+ */',...
'  user-select: none;',...
'}',...
'.caret::before {',...
'  content: "\25B6";',...
'  color: black;',...
'  display: inline-block;',...
'  margin-right: 6px;',...
'}',...
'.caret-down::before {  -ms-transform: rotate(90deg); /* IE 9 */',...
'  -webkit-transform: rotate(90deg); /* Safari */',...
'  transform: rotate(90deg); }',...
'.nested { display: none; }',...
'.active { display: block; }',...
'.propertyinput{padding:0px;display:inline-block;border:none;border-bottom:1px solid #ccc;width:100px}',...
'#indexview {',...
'  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;',...
'  font-size: 8pt;',...
'  border-collapse: collapse;',...
'  width: 100%;',...
'}',...
'td, th {',...
'  border: 1px solid #ddd;',...
'  padding: 2px;',...
'}',...
'tr:nth-child(even){background-color: #f2f2f2;}',...
'tr:hover {background-color: #ddd;}',...
'th {',...
'  padding-top: 2px;',...
'  padding-bottom: 2px;',...
'  text-align: left;',...
'  background-color: #ffeed9;',...
'  color: white;',...
'}',...
'</style>',... %'<script src="jquery.js"></script>',...%'<script src="jstree.js"></script>',...
'     <script>',...
' if (location.hash=='''')',...
'     location.hash = ''#trophic'';',...
'window.onhashchange = function() {',...
'            navbar = document.getElementById(''navigationbar'');',...
'            var all = navbar.getElementsByTagName("a");',...
'            for (var i=0, max=all.length; i < max; i++) {',...
'                href = all[i].href; href = href.substr(href.indexOf(''#''));',...
'                if (href==location.hash) { all[i].classList.add("on");} else { all[i].classList.remove("on"); }',...
'            }',...
'            var data_file = location.hash;',...
'            var http_request = new XMLHttpRequest();',...
'            try{',...
'               // Opera 8.0+, Firefox, Chrome, Safari',...
'               http_request = new XMLHttpRequest();',...
'            }catch (e) {',...
'               // Internet Explorer Browsers',...
'               try{',...
'                  http_request = new ActiveXObject("Msxml2.XMLHTTP");',...
'					',...
'               }catch (e) {',...
'				',...
'                  try{',...
'                     http_request = new ActiveXObject("Microsoft.XMLHTTP");',...
'                  }catch (e) {',...
'                     // Something went wrong',...
'                     alert("Your browser broke!");',...
'                     return false;',...
'                  }',...
'					',...
'               }',...
'            }',...
'			',...
'            http_request.onreadystatechange = function() {',...
'			',...
'               if (http_request.readyState == 4  ) {',...
'                  // Javascript function JSON.parse to parse JSON data',...
'                  //var jsonObj = JSON.parse(http_request.responseText);',...
'',...
'                  // jsonObj variable now contains the data structure and can',...
'                  // be accessed as jsonObj.name and jsonObj.country.',...
'                  document.getElementById("maindataid").innerHTML = http_request.responseText;',...
'                  var arr = document.getElementById("maindataid").getElementsByTagName(''script'')',...
'                  for (var n = 0; n < arr.length; n++)',...
'                      eval(arr[n].innerHTML)//run script inside div',...
'               }',...
'            }',...
'			',...
'            http_request.open("POST", data_file.substr(1), true);',...
'            http_request.setRequestHeader("Content-type", "application/x-www-form-urlencoded");',...
'            http_request.send("event=None");',...
'         }',...
' window.onload = window.onhashchange;',...
'// Make the DIV element draggable:',...
'',...
'function dragElement(elmnt) {',... % '  elmnt.style.position="relative";',...
'  var pos1 = 0, pos2 = 0, pos3 = 0, pos4 = 0;',...
'  if (document.getElementById(elmnt.id + "header")) {',...
'    // if present, the header is where you move the DIV from:',...
'    document.getElementById(elmnt.id + "header").onmousedown = dragMouseDown;',...
'  } else {',...
'    // otherwise, move the DIV from anywhere inside the DIV:',...
'    elmnt.onmousedown = dragMouseDown;',...
'  }',...
'',...
'  function dragMouseDown(e) {',...
'    e = e || window.event;',...
'    e.preventDefault();',...
'    // get the mouse cursor position at startup:',...
'    elmnt.style.cursor = "grabbing";',...
'    elmnt.style.opacity = 0.5;',...
'    pos3 = e.clientX;',...
'    pos4 = e.clientY;',...
'    document.onmouseup = closeDragElement;',...
'    // call a function whenever the cursor moves:',...
'    document.onmousemove = elementDrag;',...
'  }',...
'',...
'  function elementDrag(e) {',...
'    e = e || window.event;',...
'    e.preventDefault();',...
'    // calculate the new cursor position:',...
'    pos1 = pos3 - e.clientX;',...
'    pos2 = pos4 - e.clientY;',...
'    pos3 = e.clientX;',...
'    pos4 = e.clientY;',...
'    // set the element''s new position:',...
'    elmnt.style.top = (elmnt.offsetTop - pos2) + "px";',...
'    elmnt.style.left = (elmnt.offsetLeft - pos1) + "px";',...% alert(elmnt.offsetTop.toString()+" "+pos2.toString());',...
'    update_lines();',...
'  }',...
'',...
'  function closeDragElement() {',...
'    // stop moving when mouse button is released:',...
'    document.onmouseup = null;',...
'    document.onmousemove = null;',...
'    elmnt.style.cursor = "all-scroll";',...
'    elmnt.style.opacity = 1;',...
'    update_lines();',...
'  }',...
'}',...
'         function ajaxevent(name) {',...
'            var data_file = "event";',...
'            var http_request = new XMLHttpRequest();',...
'            try{',...
'               // Opera 8.0+, Firefox, Chrome, Safari',...
'               http_request = new XMLHttpRequest();',...
'            }catch (e) {',...
'               // Internet Explorer Browsers',...
'               try{',...
'                  http_request = new ActiveXObject("Msxml2.XMLHTTP");',...
'					',...
'               }catch (e) {',...
'				',...
'                  try{',...
'                     http_request = new ActiveXObject("Microsoft.XMLHTTP");',...
'                  }catch (e) {',...
'                     // Something went wrong',...
'                     alert("Your browser broke!");',...
'                     return false;',...
'                  }',...
'					',...
'               }',...
'            }',...
'			',...
'            http_request.onreadystatechange = function() {',...
'			',...
'               if (http_request.readyState == 4  ) {',...
'                  // Javascript function JSON.parse to parse JSON data',...
'                  //var jsonObj = JSON.parse(http_request.responseText);',...
'',...
'                  // jsonObj variable now contains the data structure and can',...
'                  // be accessed as jsonObj.name and jsonObj.country.',...
'                  document.getElementById("maindataid").innerHTML = http_request.responseText;',...
'                  var arr = document.getElementById("maindataid").getElementsByTagName(''script'')',...
'                  for (var n = 0; n < arr.length; n++)',...
'                      eval(arr[n].innerHTML)//run script inside div',...
'               }',...
'            }',...
'			',...
'            http_request.open("POST", data_file, true);',...
'            http_request.setRequestHeader("Content-type", "application/x-www-form-urlencoded");',...
'            http_request.send("event="+name);',...
'         }',...
'		',...
'      </script>',...
'</head>',...
'<body>',...
'',...
'<div class="header">',...
'  <h1>Allometric Trophic Network Dynamics</h1>',...
'</div>',...
'',...
'<div class="topnav" id="navigationbar">',...
'  <a href="#trophic" class="on">Trophic Network</a>',...
'  <a href="#build">Build Model</a>',...
'  <a href="#run">Run Model</a>',...
'  <a href="#analyze">Analyze Results</a>',...
'</div>',...
'',...
'<div class="row">',...
'  <div class="menucolumn"><h2>+</h2>',...
'    <div class="menudata">',...
'      <button class="button" onclick="ajaxevent(''addproducer'')">P</button>',...
'      <button class="button" onclick="alert(''consumer'')">C</button>',...
'      <button class="button" onclick="alert(''fish'')">F</button>',...
'      <button class="button" onclick="alert(''detritus'')">D</button>',...
'</div>',...
'  </div>',...
'  ',...
'  <div class="propertycolumn">',...
'    <h2>Properties</h2>',...
'    <div class="propertiesdata">',...
'    </div>',...
'  </div>',...
'  ',...
'  <div class="maincolumn">',...
'  </div>',...
'</div>',...
'',...
'</body></html>');
        end
    end

end
